//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Input/MazeInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace jia543
{
    public partial class @MazeInputs: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @MazeInputs()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""MazeInputs"",
    ""maps"": [
        {
            ""name"": ""Maze"",
            ""id"": ""26006f85-e980-490d-9e81-790b33b3320d"",
            ""actions"": [
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""c1f5b8d5-895c-40ba-b3ee-de256d64fa7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a3552b17-8d6b-453f-b851-47002308344f"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Maze
            m_Maze = asset.FindActionMap("Maze", throwIfNotFound: true);
            m_Maze_Rotate = m_Maze.FindAction("Rotate", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Maze
        private readonly InputActionMap m_Maze;
        private List<IMazeActions> m_MazeActionsCallbackInterfaces = new List<IMazeActions>();
        private readonly InputAction m_Maze_Rotate;
        public struct MazeActions
        {
            private @MazeInputs m_Wrapper;
            public MazeActions(@MazeInputs wrapper) { m_Wrapper = wrapper; }
            public InputAction @Rotate => m_Wrapper.m_Maze_Rotate;
            public InputActionMap Get() { return m_Wrapper.m_Maze; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MazeActions set) { return set.Get(); }
            public void AddCallbacks(IMazeActions instance)
            {
                if (instance == null || m_Wrapper.m_MazeActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_MazeActionsCallbackInterfaces.Add(instance);
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
            }

            private void UnregisterCallbacks(IMazeActions instance)
            {
                @Rotate.started -= instance.OnRotate;
                @Rotate.performed -= instance.OnRotate;
                @Rotate.canceled -= instance.OnRotate;
            }

            public void RemoveCallbacks(IMazeActions instance)
            {
                if (m_Wrapper.m_MazeActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IMazeActions instance)
            {
                foreach (var item in m_Wrapper.m_MazeActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_MazeActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public MazeActions @Maze => new MazeActions(this);
        public interface IMazeActions
        {
            void OnRotate(InputAction.CallbackContext context);
        }
    }
}
